run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/fullstacks-gmbh/universal-airgapper
