# .pre-commit-config.yaml
repos:
  # overall file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: destroyed-symlinks
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
        exclude: |
          (?x)(
              ^creds/|
              ^docs/|
              ^README.md
          )

  # commit-message & author
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args:
          - -cgeneral.verbosity=2
          - -cgeneral.ignore=B6
          - -cgeneral.ignore-merge-commits=true
          - -cgeneral.regex-style-search=True
          - -cgeneral.staged=true
          - -ctitle-max-length.line-length=100
          - '-ctitle-match-regex.regex=^(feat|fix|try|maintain)!?(\(.*\))?:.+|^Merge branch.*'
          - --msg-filename

  # Go formatting, vetting, linting, testing (uses binaries from nix flake)
  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: golangci-lint fmt ./...
        language: system
        types: [ go ]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [ go ]
        pass_filenames: false
        always_run: true

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        types: [ go ]
        pass_filenames: false
        always_run: true

      - id: go-test
        name: go test
        entry: go test ./...
        language: system
        types: [ go ]
        pass_filenames: false
        always_run: true
