apiVersion: batch/v1
kind: CronJob
metadata:
  name: airgapper-cronjob
spec:
  schedule: "0 0,12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: airgapper
              image: ghcr.io/fullstacks-gmbh/universal-airgapper:latest
              command: ["/airgapper"]
              args: ["sync", "--config", "/mnt/config/", "--credentials", "/mnt/creds/"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
                - name: config-volume
                  mountPath: /mnt/config/config.yaml
                  subPath: config.yaml
                - name: secrets-git
                  mountPath: /mnt/creds/git.yaml
                  subPath: git.yaml
                - name: secrets-image
                  mountPath: /mnt/creds/image.yaml
                  subPath: image.yaml
                - name: secrets-helm
                  mountPath: /mnt/creds/helm.yaml
                  subPath: helm.yaml
          restartPolicy: Never
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
          volumes:
            - name: config-volume
              configMap:
                name: airgapper-config
            - name: secrets-git
              secret:
                secretName: airgapper-secrets-git
            - name: secrets-image
              secret:
                secretName: airgapper-secrets-image
            - name: secrets-helm
              secret:
                secretName: airgapper-secrets-helm
